package embed

const (
	templateDependenceRes = `// Code generated by shures; DO NOT EDIT.
package {{.pkg }}

import (
    "github.com/shuxs/go.shures/res"
)

{{- with $model := . }}
var {{ $model.var }} = &res.FS{
	Files: _{{ $model.var }}Files,
	Dirs: _{{ $model.var }}Dirs,
}

var _{{ $model.var }}Files = res.FileMap {
{{- range $dir := $model.dirs }}

	"{{ $dir.Path }}": {
	    Path:        "{{ $dir.Path }}",
	    FileName:    "{{ $dir.FileName }}",
	    FileIsDir:   true,
    },

    {{- range (index $model.files $dir.Path) }}

	"{{ .Path }}": {
	    Path:        "{{ .Path }}",
	    FileName:    "{{ .FileName }}",
	    FileSize:    {{ .FileSize  }},
	    FileModTime: {{ .FileModTime }},
	    Compressed:  ` + "`" + `{{ .Compressed }}` + "`" + `,
    },

	{{- end }}

{{- end }}
}

var _{{ $model.var }}Dirs = res.DirMap {
{{- range $dir := $model.dirs }}
	"{{ $dir.Path }}": {
		{{- range (index $model.files $dir.Path) }}
		_{{ $model.var }}Files["{{ .Path }}"],
		{{- end }}
	},
{{- end }}
}

{{- end }}
`
)

/*



*/