package embed

const (
	templateDependenceRes = `// Code generated by shures; DO NOT EDIT.
package {{ .Package }}

import (
    "github.com/shuxs/go.shures/res"
)

{{- with $model := . }}
var {{ $model.Name }} = &res.FS{
	Files: {{ $model.VarFiles }},
	Dirs: {{ $model.VarDirs }},
}

var {{ $model.VarFiles }} = res.FileMap {
{{- range $dir := $model.Folders }}

	"{{ $dir.Path }}": {
	    Path:        "{{ $dir.Path }}",
	    FileName:    "{{ $dir.FileName }}",
	    FileIsDir:   true,
    },

    {{- range (index $model.FileMap $dir.Path) }}

	"{{ .Path }}": {
	    Path:        "{{ .Path }}",
	    FileName:    "{{ .FileName }}",
	    FileSize:    {{ .FileSize  }},
	    FileModTime: {{ .FileModTime }},
	    Compressed:  ` + "`" + `{{ .Compressed }}` + "`" + `,
    },

	{{- end }}

{{- end }}
}

var {{ $model.VarDirs }} = res.DirMap {
{{- range $dir := $model.Folders }}
	"{{ $dir.Path }}": {
		{{- range (index $model.FileMap $dir.Path) }}
		{{ $model.VarFiles }}["{{ .Path }}"],
		{{- end }}
	},
{{- end }}
}

{{- end }}
`
)
